version: "2"

# options for analysis running
run:
  go: "1.24"
  timeout: 1m
  issues-exit-code: 1

linters:
  enable:
    - gocyclo
    - errcheck
    - godox
    - wsl
    - lll
    - gofumpt
    - nestif

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    gocyclo:
      min-complexity: 18

    lll:
      line-length: 140

    nestif:
      min-complexity: 4
