version: "2"

# options for analysis running
run:
  go: "1.24"
  timeout: 1m
  issues-exit-code: 1

# these are top-level now, not under run
skip-dirs: []

linters:
  enable:
    - gocyclo
    - errcheck
    - godox
    - gci
    - wsl
    - lll
    - gofumpt
    - nestif

  settings:
    godox:
      severity: warning

    errcheck:
      check-type-assertions: true
      check-blank: false

    gocyclo:
      min-complexity: 18

    gci:
      sections:
        - standard
        - default

    lll:
      line-length: 140

    nestif:
      min-complexity: 4
