version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "defer"
