run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode
    - gofmt

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "defer"
