apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: leader-elector
  name: leader-elector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-elector
subjects:
  - kind: ServiceAccount
    name: leader-elector
